name: Deepslate
version: 1.0
api-version: 1.19
main: fr.pickaria.Main
author: Quozul
description: The main plugin of Pickaria.
dependencies:
  - name: Bookshelf
    required: true
    bootstrap: false
  - name: PickariaSpawner
    required: true
    bootstrap: false
  - name: Vault
    required: true
    bootstrap: false
  - name: Votifier
    required: true
    bootstrap: false
  - name: Towny
    required: true
    bootstrap: false
  - name: LuckPerms
    required: true
    bootstrap: false
load-after:
  - name: Bookshelf
    bootstrap: false
  - name: LuckPerms
    bootstrap: false