name: Deepslate
version: "1.0"
api-version: "1.20"
main: fr.pickaria.Main
author: Quozul
description: The main plugin of Pickaria.
loader: fr.pickaria.Loader

dependencies:
  bootstrap:
    PickariaSpawner:
      required: true
      join-classpath: true
      load: BEFORE
    Vault:
      required: true
      join-classpath: true
      load: BEFORE

  server:
    PickariaSpawner:
      required: true
      join-classpath: true
      load: BEFORE
    Vault:
      required: true
      join-classpath: true
      load: BEFORE
