name: Deepslate
version: 1.0
api-version: 1.19
main: fr.pickaria.Main
author: Quozul
description: The main plugin of Pickaria.
depend:
  - Bookshelf
  - PickariaSpawner
  - Vault
  - Votifier
  - Towny

commands:
  menu:
    usage: /menu
    description: Ouvre le menu du serveur.

permissions:
  pickaria.messages.join:
    description: Allow the join message to be visible.
    default: op
  pickaria.messages.quit:
    description: Allow the quit message to be visible.
    default: op
  pickaria.messages.advancement:
    description: Allow the advancement messages to be visible.
    default: op