name: Bookshelf
version: 1.0
api-version: 1.19
main: fr.pickaria.Main
author: Quozul
description: A plugin including all dependencies required for the main plugin.
dependencies:
  - name: PickariaSpawner
    required: true
    bootstrap: false
  - name: Vault
    required: true
    bootstrap: false
  - name: Votifier
    required: true
    bootstrap: false
  - name: Towny
    required: true
    bootstrap: false
  - name: LuckPerms
    required: true
    bootstrap: false
load-before:
  - name: Deepslate
    bootstrap: false